# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: "Trabalho de Conclusão"

# gatilhos / triggers - regras de disparo

on:
    # manual
    workflow_dispatch:

    # push na main
    push:
      branches:
        - main

    # agendada a cada 30 minutos
    schedule:

      - cron: '*/30 * * * *'

#tarefas dentro da pipeline = jobs

jobs:
    #nome do job
    tests:
        # maquina onde o job vai rodar
        runs-on: ubuntu-latest

        # passos do job
        steps:
            # clone do projeto
            - uses: actions/checkout@v4
            
            # instalção do node
            - uses: actions/setup-node@v4
              with:
                  node-version: 24.x

            # instalação de dependências
            - name: Instalando dependências
              run: npm ci

            # execução de teste
            - name: Execução de testes e geração de relatório
              run: npm run test

            # Publicar relatório de testes
            - name: Salvando relatório de testes
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: Relatório de Testes
                path: mochawesome-report